issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:shopware/SwagLanguagePack:.*
claim_pattern:
  workflow_ref: shopware/SwagLanguagePack/.github/workflows/prepare_release.yml@.*

permissions:
  contents: write
