name: Build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: shopware/github-actions/build-zip@main
        with:
          extensionName: ${{ github.event.repository.name }}
