name: Build
on:
  pull_request:
  push:
    branches:
      - 6.6.x

jobs:
  build:
    uses: shopware/github-actions/.github/workflows/build-zip.yml@main
    with:
      extensionName: ${{ github.event.repository.name }}
