name: Build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    uses: shopware/github-actions/.github/workflows/build-zip.yml@main
    with:
      extensionName: ${{ github.event.repository.name }}

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
      -
        name: Generate Dockerfile
        run: |
          cat <<EOF > Dockerfile
            ARG BASE_IMAGE
            ARG PLUGIN_NAME
            FROM ${BASE_IMAGE}

            COPY *.zip /var/www/html/plugin.zip

            RUN cd /var/www/html/ \
                && mkdir -p custom/plugins/${PLUGIN_NAME} \
                && unzip -d custom/plugins/${PLUGIN_NAME} plugin.zip \
                && chown www-data:www-data -R custom/plugins/${PLUGIN_NAME} \
                && rm plugin.zip
          EOF

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login into Github Docker Registery
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/ci-e2e:${{ github.run_id }}
          file: .gitlab/docker/dev/Dockerfile
          build-args: BASE_IMAGE=ghcr.io/pweyck/platform/ci-e2e:trunk,PLUGIN_NAME=${{ github.event.repository.name }}