name: PHP
on:
  pull_request:
    paths:
      - '**/*.php'
      - .github/workflows/php.yml
  push:
    paths:
      - '**/*.php'
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: phpunit
        uses: shopware/github-actions/.github/actions/phpunit@add-composite-actions
        with:
          extensionName: ${{ github.event.repository.name }}
          shopwareVersion: trunk
          uploadCoverage: false
