name: Release to Store
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Prepare Release"]
    types:
      - completed

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ vars.RELEASE_BRANCH }}
          fetch-depth: 0
      - uses: shopware/github-actions/store-release@main
        with:
          extensionName: ${{ github.event.repository.name }}
          accountUser: ${{ secrets.SHOPWARE_ACCOUNT_USER }}
          accountPassword: ${{ secrets.SHOPWARE_ACCOUNT_PASSWORD }}
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          # As we are currently releasing from 6.6.x we checkout the repo separately
          skipCheckout: true
