name: Release to Store
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: shopware/github-actions/store-release@main
        with:
          extensionName: ${{ github.event.repository.name }}
          accountUser: ${{ secrets.SHOPWARE_ACCOUNT_USER }}
          accountPassword: ${{ secrets.SHOPWARE_ACCOUNT_PASSWORD }}
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          skipCheckout: true
