name: Release to Store
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: shopware/github-actions/store-release@main
        with:
          extensionName: ${{ github.event.repository.name }}
          clientId: ${{ secrets.SHOPWARE_CLI_ACCOUNT_CLIENT_ID }}
          clientSecret: ${{ secrets.SHOPWARE_CLI_ACCOUNT_CLIENT_SECRET }}
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          skipCheckout: true
