name: Manual job to test cross workflow download
on:
  workflow_dispatch:

jobs:
  find:
    runs-on: ubuntu-latest
    permissions:
        checks: read
    steps:
        - name: find build run
          run: |
            curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/commits/${{ github.ref }}/check-suites
            
